services:
- type: pserv
  name: mysql
  plan: standard
  env: docker
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: prokure
  - key: MYSQL_USER
    value: root
  - key: MYSQL_PASSWORD
    value: Sammy1234
  - key: MYSQL_ROOT_PASSWORD
    value: Sammy1234
